* 정규직과 비정규직

특정 귀족 전담 모험가가 일종의 정규직이라면, 모험가 길드에 소속된 이들은 비정규직이라고 할 수 있다.

일종의 '프리타'라는 내용으로 볼 수 있다.

지배층 입장에서는 일반적인 영주민에비해 비정규직이 너무 많아지면 문제가 될 수 있기 때문에, 제대로 된 인물들을 뽑아 자신의 권력을 공고히하기위한 자원을 수급하면서도 지나친 규모의 확대를 막기 위해 모험가 길드의 크기를 일정정도로 유지해야할 필요도 있다. 이 부분이 일종의 갈등포인트가 될 수 있다.

* 불용 포인트

이안은 고의적으로 자신의 지력은 평범수준, 기교는 최고 수준, 근력과 민첩은 일반미만으로 잡았다. 그리고 마나는 아예 0로 만들어서 여신으로부터 안쓰러움을 산다.
추가로 이안이 고른 [기화], [촉매 작용], [성분 동기화], [추출분류], [거지근성]은 일부는 나쁘지않거나 그저 그런 수준이며 실제 전투에서는 직접적인 타격이 거의 없다시피하다.
[분산사고] 역시 마법사나 전사등 직접 스킬을 사용하는 캐릭터에게는 굉장히 유용할 수는 있지만 제대로된 전투스킬도 없고 마나는 0으 찍을 이안에게는 아무 필요없는 수치였다..

기술의 가치는 보통 직접적인 전투효과나 발동되었을 때의 수치 기준이기 때문에 여신이 관리하는 시스템입장에서는 말그대로 쓰레기 수준에 불과한 것.하물며 실제 생명체에는 영향을 줄 수 있는 것이 성분 동기화뿐인데, 그나마도 다른 조건들은 소재나 무생물에만 가능하니 그 마저도 쓸모는 한 없이 제로에 가까왔다.

그렇기 때문에 기본적으로 전생 소환된 특전 2개 ([초감정], [소재채취명인])에 부가해서 [거지근성] (아무데서나 휴식 가능. 1시간 짧은 휴식시 50% 회복)을 강화하여 [초회복]으로 업그레이드해주고 [분산사고]도 [강화된 분산사고]로 향상시켜준다, 고독사하지않도록 최소 1명의 여성은 그의 옆에 있을 수 있도록 [좋은 인연]도 덤으로 준다.

이렇게 도와준 이유는 그의 총합 스탯이 너무 낮아, 남아버린 에너지가 잘못 역류해 세계에 잘못된 영향을 줄까 걱정해서였다.
