* 스탯 설정 

주인공이 이세계에 소환되어 새로운 이름과 몸(17세의 몸)을 받으며 스킬을 선택하게 된다.  관리자인 여신이 스탯과 스킬을 설정하라고 제시해주고, 주인공은 어떻게 설정해야할지 고민을 시작한다. 원래 세상에서도 오버스펙을 찍는 것보다는 기발한 조합을 조하했기에 나름 약해보이면서도 강한 설정을위한 고민의 시간이 길어진다. 관리자는 세상에는 일종의 한계가 정해져있어, 필요이상의 스탯이나 스킬을 찍으면 균형을 위해 세계가 위험한 인자를 파괴한다고, 한 용사의 사기적인 스탯과 그 용사가 몰락하는 과정을 보여준다.

(크게 당황하며 놀람)

놀라는 주인공은 아예 처음부터 스탯을 평범한 수치로 낮추고 슬슬 여신의 눈치를 본다. 소환전에는 게임을 즐기던 주인공은 자기가 했던 방식을 응용해서 뭔가 쓰레기같고 생산직 같아보이지만 응용만 잘하면 사기적인 스킬들만 뽑아서 적용한다. (설정한 스탯과 기술에 대해 간략히 설명해준다.)

관리자인 여신이 그 내용을 보고 무척이나 안쓰러워하며 별도의 특전 스킬과 특전을 주고 새로운 세계로 행운을 빈다며 보내준다. 



* 소환이후 일상 

주인공은 어느 초원에서 깨어난다. 

  뭐 보통은 이때쯤 여주인공이 꺄악하고 위기에 빠져서 내가 구해주는게 클리셰이긴한데..

혼잣말을 중얼거리며 천천히 일어서는 드린을 주변을 살피며 여신이 선물해준 [신의눈]을 전개했다. 주변에 널려있는 풀중에 제법 괜찮은 약초들이 보였다. 주변의 돌을 찾아, 조심스럽게 땅을 파서 약초들을 채집했다.

  들쑥: 품질 S 등급. 해독제 재료. 과용하면 복통이나 설사를 일으킴
  활력초: 품질 S 등급. 힐링포션이나 스태미너 포션 재료. 쓴 맛이 강함

처음 수집한 것부터 S등급이라니 굉장하다고 놀란다. 이어 다양한 풀과 재료를 수집하며 조그마한 자루를 채우고는 슬슬 안전한 장소를 찾으러 이동하기 시작한다.

이안은 전생 전 서바이벌 지식을 활용하여 숲에 임시 거처를 세우고 휴식을 취한다.

* 숲에서의 위기 

[초회복]덕으로 1시간 정도의 휴식만으로  완전히 회복된 이안은 주변을 둘러본다. 그리고, 자신의 주변에 무엇인가 육식동물의 비린내를 맡는다. 회색늑대 무리가 이안의 주변을 둘러싸게되고, 이안은 자신이 채집했던 일부 독초를 사용해 회색늑대를 식중독상태로 만들어 무력화시킨다. 
회색늑대가 물러난 후 이안은 안도의 숨을 내쉬며, 다시 올 위협을 막기위해 이안은 주변에서 세이지를 찾아 모닥불에 태우고 그 연기로 자신을 숨긴다. 

* 명복

숲 속에도 아침이 밝아왔다. 잎새 사이사이로 흘러들어온 햇빛은 적지않은 온기로 이안의 몸을 뎁혀주었다.

기화..

밤이슬에 몸이 젖은 이안은 일단 젖은 옷을 말렸다. 생명체에는 쓸 수 없었지만, 소재나 물건에는 그래도 유용하게 쓰이는 [기화]덕분에 옷은 어느새 보송보송해졌다. 주변의 물에서 더러운 성분을 거르고 천천히 이안은 몇 개인가의 불씨를 챙기고는 발걸음을 옮기기 시작한다.

어제 보았던 혈엽 쑥이 지천으로 나있는 풀숲을 지나, 나무 아래에서 자라는 감초를 몇 뿌리 땄다. 독성을 중화하거나, 다른 약초와 조합할 때 도움이 되는 풀이었다. 단맛이 나는 감초성분을 추출해 조금씩 음미했다. 문명사회에서 느꼈던 감미. 잠시나마 숲속의 길에서 이안은 비로서 자신이 문명을 떠난 다른 세계에 왔다는 것을 느꼈다.

혈엽쑥풀더미를 지나, 소롯길로 막 나온 순간이었다. 이안의 눈에 한 나무 그루터기의 하얀 물체가 눈에 띄었다. 사람과 늑대의 뼈. 인골에는 헤진 옷이 시간의 경과를 보여주고 있었고, 살점이 다 없어진 쇠락한 늑대의 뼈에는 한 때는 날카로왔을 단검이 꽂혀있었다. 아마도 숲에서 나타난 늑대와 길을 가던 여행자가 함께 목숨을 잃었을 그런 모양이었다.

이안은 천천히 두손을 모아 명복을 빌었다. 누구인지는 모르지만, 부디 좋은 곳으로 떠났기를 바라는 전생에서 나온 습관적인 기도. 명복을 빌며, 무덤을 파기 시작한다. 왜인지는 몰랐다. 하지만, 어쩌면 어젯밤 자신도 똑같은 처지로 숲속에서 스러져가는 시체가 되었을 수 있다는 생각이, 제대로된 무덤을 만들어줘야겠다는 생각으로 이어졌을지도 몰랐다.

조그마한 무덤을 파고, 최대한 조심스럽게 시체를 안장해주었다. 딸랑거리며 시체의 목에서 떨어진 인식표가 주인이 모험가였고, 오로트의 모험가 길드 소속임을 말해주었다. 흙을 덮고, 돌로 야생동물들이 파해치치못하게 만든 후에야 이안은 겨우 휴식을 취했다.

허약한 몸. 금방 바닥나는 체력. 자신이 만든 설정이었지만 쓴 웃음이 났다. 아마도 여신이 보였던 그 호의는 지금 자신이 생각해도 나올 수 밖에 없었을  것이었다.

숨을 고르며, 휴식을 취하면서 이안은 여행자가 남긴 물건들을 조심스럽게 정리하기 시작했다. 이제는 다 슬어버린 가방속에는 포션이 들어있었을 빈 병 몇개와 다 썩어버린 건조식량과 육포가 몇 장, 그리고 짤랑거리는 몇 개의  동화와 은화 한개가 전부였다.

가난하고 미래를 알 수 없는 삶. 모험가라는 삶은 하루하루를 연명하는 것만으로도 힘든 삶일 것이다. 야수나 마물과 싸우고, 도시의 잡다한 일을 해결해주고, 현상금이 걸린 도적을 찾아 헤메고. 어쩌면 이 모험가역시 어떤 일을 맡았지만 다시 돌아오지 못했을 길을 떠난 것일지도 몰랐다. 어떤 삶을 살았고, 어떤 인연이 있었을까.

짧은 휴식을 마치고, 이안은 서서히 자리에서 일어났다. 고독하게 남겨진 무덤에 작은 꽃 하나를 올리며, 천천히 고개를 숙인다. 오로트에 가면 모험가 길드에 들를 것이다. 그리고 이름표를 건네주고 숲에서 그의 죽음이 더이상 고독하지않도록 알려줘야지. 그런 다짐을 하며, 이안은 삭은 가방을 챙겨 바구니에 넣고 다시 길을 옮기기 시작한다.

* 소란 속으로   

(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 묘사나 독백을 강화하도록 하라.) 

멀리 언뜻 언뜻 보이는 도시의 전경을 바라보며 이안은 천천히 숲속을 걸었다. 보통의 사람 눈에는 이름 모를 들꽃이 핀 길이겠지만, 이안에게는 쑬모가 분명한 소재들로 가득했다.

은잎 박하. 벌레를 잡는데 특효지. 적거미 쐐기풀은 가려움증을 일으키니 유용하고. 

하나하나 약초의 이름과 약효를 되네이며 이안은 발걸음을 옮긴다. 길가에 피는 잡초라고 외면받지만, 저마다의 효용과 가치는 분명했다. 사람들이 못알아주는 것일뿐. 세상은 이미 유용함과 가치로 가득 차 있었다.

한갓길에 앉아 물을 마쉬며 휴식을 취한다. 어느덧 머리위를 넘어 슬슬 오후로 달려가는 해를 바라면서, 이안은 가만히 손부채질을 한다.

느긋하다..

시간도 멈춘듯한 숲속에서 편안히 휴식을 취했다. 선선한 바람. 따스한 햇빛. 그리고... 이안은 눈을 번쩍 떴다.

희미하게 들리는 금속의 소리. 사이사이로 들리는 절박한 외침과 비명소리. 무엇인가 일어나고 있다는 생각에 이안은 자리에서 벌떡일어났다. 그리고 생각을 다 추스리지못하는 상태에서 소리가 나는 쪽으로 달려갔다. 

* 전투

헉헉헉..

숨이 턱밑까지 차올랐다. 빈약한 체력으로 달리다보니 어느새 가슴은 터질듯이 두근거렸다. 돌부리에 채이고, 나무에 긁혔지만 이안은 멈추지않았다. 방금 전 그가 묻어준 모험가가 떠올랐다. 누군가의 애도나 슬픔을 나누지 못하는 안타까운 죽음을 막고 싶었다.

숲 한쪽에서의 상황이 펼쳐졌다. 몇 마리인가의 고블린이 이미 죽어 땅에 누워있었고, 호위 기사로 보이는 사람 역시 가쁜 숨을 흘린채 피를 흘리며 땅에 쓰러져있었다. 그 너머에는 전사와 도적으로 보이는 경장 차림의 남녀가 필사적으로 남은 고블린의 공격을 막아내고 있었다.

대도를 든 전사와, 단검으로 무장한 여성 도적. 전사가 큰 칼로 단번에 고블린을 밀어내면 도적은 날렵하게 빈틈을 찌르는 훌륭한 협동 플레이였다. 그리고 그 뒤에는 그들이 보호하려고 애쓰는 귀족으로 보이는 아가씨가 메이드로부터 보호받고 있었다.

넷, 다섯 마리..

이안은 눈으로 고블린을 세며 상황을 면밀히 분석하기 시작했다. 가벼운 클럽과 방패로 무장한 고블린들이었지만, 일단 수가 많았다. 어린아이보다 조금 큰 키였지만, 반대로 상대할 때는 그 작은 키때문에 방어하기 까다로운 하반신을 노리는 전술. 게다가 숫자역시 많았기 때문에, 전사와 도적은 여간해서 숫자를 줄이지 못하고 있었다.

이안은 약재가 담긴 바구니를 열어, 역재를 뒤지기 시작했다. 자기가 직접 나서 공격하는 것은 그냥 딱딱한 돌에 계란하나 던지는 꼴이었다. 그보다는 다른 방법이 필요했다.

광대버섯...

환각이나 착란을 일으키는 독버섯이 눈에 들어왔다. 

타타탁..

이안이 재빨리 모아둔 불쏘시개를 모으고 조심스럽게 갈무리해둔 불씨로 불을 지폈다. [촉매반응]을 통해 순식간에 불이 붙은 불소시개에 [기화]시켜 바싹 말린 광대버섯을 던져놓았다.

광대버섯의 연기가 매캐하게 올라오자 [성분 동기화]로 환각성질을 뽑아 고블린에게 뿌렸다.

키익. 킥. 크큭.

환각성분이 고블린을 덮치며 착란을 일으키기 시작한다. 눈앞에 전사와 도적이 거대해지며, 무시무시한 괴물로 변화했다. 당황해 뒷걸음치던 고블린은 같은 편의 모습도 자신을 공격하려는 마물로 보였다. 갑작스럽게 고블린들의 움직임이 변하자, 전사와 도적은 때를 놓치지않고 공격을 시작한다.

푹, 서걱-.

외마디 비명을 지를새도 없이 고블린들은 하나하나 정리되어갔다. 위기 일발의 순간이었지만, 이안이 만들어준 찰나의 틈을 놓치지않고 상대를 무너뜨린 모습은 확실히 프로다웠다.

장내가 정리되고, 전사와 도적이 가쁜 숨을 쉬며 겨우 숨을 돌리는 것을 확인하고, 그제서야 이안은 천천히 숲에서 나와 그들 앞에 선다. 경계심에 잠깐 움찔대던 둘 이었지만, 앞에 나타난 것은 병약해보이는 청년의 모습을 한 이안이었다. 무엇인가를 태운 듯한 검댕을 손에 잔뜩 묻히고, 손은 마치 항복하듯 든 채로...

* 도시로...

기사들은 가쁜 숨을 내쉬고 있었다. 치료약이 있다면야 어떻게 해결해볼 수 있겠지만, 쓸 수 있는 것은 얼마 안되는 지혈용 붕대와 약간의 포션뿐이었다. 그나마도 방금전 전투에서 사용했는지 포션은 반도 남지 않았다.

이안이 붕대로 기사의 상처를 지혈하는 동안 전사와 도적은 귀족 아가씨쪽으로 가서 상태를 살피고 있었다. '사람의 목숨값도 차이가 있구만.' 쓴 웃음을 지으며 이안은 약초가 담긴 가방을 열어 몇 개인가의 혈잎 쑥을 뽑아들고는 손으로 짓이기기 시작했다.

추출분류.. 

원래대로라면 짓이기진 덕에 성분들이 마구 섞였겠지만 이안의 [추출분류]로 지혈성분과 회복 성분이 분리되어 따로 모였다. 이안은 상처 사이에 추출한 성분을 넣고는, 다시 꼼꼼히 붕대로 묶었다. [손재주]가 응급치료에도 적용이 되는지, 상처에서의 출혈은 곧 멈추었고, 두 기사의 호흡도 안정화되었다.

치료가 익숙한가본데.. 치료사인가?

다가온 전사가 처치가 한참인 이안에게 물어왔다.

내 이름은 가드, 그리고 저 쪽의 일행은 리라다.

자기 소개를 하는 전사 가드에게 이안은 그를 올려다보았다. 탄탄한 근육질의 몸에, 가죽 경장 갑옷을 입은 건장한 사내였다. 싸움탓에 몸 여기저기에는 상처가 나있었지만, 그럼에도 지친 기색없이 당당하게 서있었다. 등 뒤에 수납한 대도는 그의 등을 거의 뒤덮을 만큼 컸었는데도, 아까의 싸움에서는 보통 장검처럼 휘둘렀을 정도의 강력한 용략. 

저는 이안이라고합니다. 치료사(힐러)는 아니고 연금술사입니다. 약간의 치료는 압니다만..

이안은 가드의 눈에서 기대가 순식간에 실망으로 바뀌는 것을 눈치챌 수 있었다. 전투에서 바로바로 지원을 해주는 치료사와는 달리 연금술사는 아무 도움이 되지못했다. 포션이나 폭탄 플라스크등 소모품을 만들거나 재료 수급등에는 유용했지만, 전투에서의 가치는 제로(0). 냉랭해진 눈빛 만큼이나 그의 반응도 퉁명스러워졌다.

치료해준 것은 고맙긴한데, 우린 빨리 이동해야돼. 너, 우릴 도울 수 있겠어?

가드는 어느샌가 이안을 하인을 부리듯 하대하기 시작한다. 전사. 전투에서 압도적인 기여를 하는 그런 인물앞에 연금술사는 그냥 편하게 뒤에서 꿀만빨다가 전투가 끝나면 나와 재료나 챙기고, 뒷정리나 하는 짐꾼이나 마찬가지였다. 그의 태도 변화에 이안은 살짝 빈정이 상했지만, 꾹 참을 수 밖에 없었다. 현실의 무게는 너무나도 쉽고, 빠르게 다가왔다.

아.. 예예.. 일단 기사님들을 한쪽에 모시고, 도시로 이동하죠.
그럼 마차에 기사님들을 태우도록 해. 리라. 넌 먼저 오로트에 가서 사람을 불러와줘. 가급적 빨리 이동해야하니까.
응, 알았어 가드. 

물을 들인듯한 연보라 머리칼의 여도적이 그제야 이쪽을 보며 답을 했다. 그 얼굴을 보며 이안은 잠깐 멍하니 바라보았다. 너무 예뻐서 넋이 나갈 정도였다. 가죽 갑옷은 일부러 그렇게한듯 몸의 굴곡을 따라 타이트하게 붙어있었다. 티하나없이 깨끗한 피부는 험한 전장을 구르는 도적에게는 어울리지 않을 정도로 맑고 깨끗했다. 방금전까지 힘든 전투를 벌였지만, 그녀의 표적은 내색하나없이 밝고 명령하기만 했다.

으응~ 힘들다. 그나마 막판에 고블린들이 머뭇대서 다행이야. 그리고 역시 가드야. 한 방에 휩쓸어버리다니.. 다링~

가드에게 찰싹붙어 애교를 부리는 리라를 보고, 그제야 이안은 두 사람 사이를 알 수 있었다. '연인사이인가 보군.' 파티를 차리는 동기야 여러 방식이 있겠지만, 아마도 이들은 서로 사귀면서 자연스럽게 연인이 되었거나 아니면 그 반대였을 것이다.

씁쓸하게 웃으며, 기사들의 갑옷을 정리해주면서 이안은 남은 짐을 정리하기 시작했다. 고블린들의 시체를 한데 모으고, 불을 지핀다. 눈에 띄지 않게끔 몰래 [촉매반응]을 써서 빠르게 시체를 정리하는 와중에 그의 눈에는 리라가 떠나자마자 귀족 영애에게 달라붙어 은근한 추파를 던지는 가드가 보였다.

'속물'

요령좋은 성격이라 할 수 있었지만, 방금까지 여도적의 애정을 듬뿍받았던 전사의 태세변화에 이안은 맘이 편치 않았다.

고맙습니다. 전사님.. 전사님이 아니었다면 저희는..
가드라고 불러주십시오. 아가씨. 무사하셔서 다행입니다. 마을까지 보호해드릴테니 걱정하지 마십시오.

귀족 아가씨의 눈에는 가드가 백마의 왕자라도 될 듯 보였을 것이다. 그 옆의 메이드의 눈에도 가드는 늠름하면서도 정의감 넘치는 그런 남자로 비춰보였을 것이다. 영웅을 바라보는 애틋한 눈빛. 아마 평생가도 자신은 받아볼 수 있을지 없을지 모를 그런 눈빛이었다. 씁쓸함을 느끼며, 이안은 마차의 준비가 완료되었음을 알리고 일행들의 출발을 돕는다. 

으례 그랬듯이, 마차 뒤를 따르며, 이안은 찬찬히 마차를 바라본다. 마차를 보는 전사. 사람들이 생각하는 영웅의 모습일 터였다. 그런 사람들에게 뒤를 받치는 자신과 같은 존재는 있으나마나한 존재. 마음속에 쓴물이 올라오는 듯한 감각을 느끼며, 이안은 피로한 발을 옮긴다. 오늘은 그래도 노숙이 아니라, 제대로 된 숙소에서 묵어볼 수 있다는 희망을 가지고, 도시 오로트를 향하는 그였다.

* 모험가 길드

두 시간을 걸려 마차는 오로트에 도착했다. 리라는 어느새 도시의 귀족에게 연락했는지, 도시의 도개교앞에는 경호원들과 집사로 보이는 사람들이 마중나와있었다.

아이린 아가씨를 구해주어서 감사합니다.
전사라면 마땅히 해야할 일입니다. 무사하셔서 제가 기쁩니다.

당당한 모습으로 영웅처럼 말하는 가드. 하지만 그의 마차에서의 모습에 이안은 맘이 편치 않았다. 가드의 곁에는 리라가 너무나 기쁜 표정으로 가드를 바라보며 웃고 있었다. 사랑하는 사람을 누군가가 인정해주는 것이 기쁘다는 듯이, 순수한 기쁨으로 터져나오는 그런 티없이 맑은 경애의 눈빛이었다.

조만간 백작가로 모시라는 백작님의 말씀이셨습니다. 부디 모실 수 있도록 해주십시오.
...!

가드의 눈이 크게 떠졌다. 그의 눈에서 보인 그 광채. 이안은 익히 보아왔던 탐욕이라는 광채가 서린 그의 눈을 보며 나직이 한 숨을 쉬었다. 사회에서 보아왔던 승진에 대한 갈망. 더 많은 돈에 대한 열망. 더 나은 자리에로의 욕망. 그 익숙했던 빛이 그의 눈에 서려있었다.

오늘은 숙소에서 푹 쉬자, 가드.
...

가드의 옆에서 즐거운듯 이야기하는 리라에 대한 가드의 묵직한 침묵에 이안은 가슴이 철렁거렸다. 자신이 신경쓸 필요는 없었지만, 왠지 알 수 있을 것 같은 전개. 이제 잡을 수 있는 새로운 기회를 얻은 저 남자가 어디로 향할지 이안은 짐작할 수 있었다.

리라..
응? 왜? 
난 먼저 갈 곳이 있어?
거기가 어딘데?
일단 대장간에서 무기랑 방어구 손질도 해야하고 해야하니 먼저 길드에가서 보고하고 있어.
아.. 그래, 그럼. 알았어. 그럼 빨리와. 기다릴게.

기다린다. 리라의 목소리에서 살짝 드러난 아쉬움. 그리고 막연하게 떠오르는 불안한 불화. 어쩌면 리라도 어렴풋이 느끼고 있을지도 몰랐다. 자신이 연인이라 생각하는 남자의 마음이 서서히 멀어지는 그 어렴풋하지만 확고하게 다가오는 직감적인 느낌을.

뚜벅두벅.

뒤도 돌아보지않고 제갈길을 가는 가드. 그리고 왠지 쓸쓸한 모습으로 멍하니 가드를 바라보는 리라. 이안은 그 모습에 안타까움을 느끼지만, 자신이 나설 곳은 아니라는 생각이 앞섰다.

아.. 저..

겨우 어렵게 입을 뗀 이안을 리라가 바라본다. 아름답지만, 살짝 왠지 붉어진 눈을 한채로..

저도 모험가 길드까지 동행해도 될까요? 등록이 필요해서...

핑게같은 부탁을 하며 조심스럽게 이안은 그녀를 차마 바라보지못하고 손을 꼼지락거리며 부탁했다.

* 연금술사 등록 



(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 묘사나 독백을 강화하도록 하라.) 

오후 늦은 길드는 퀘스트 결과를 제출하러온 모험가들과 그들이 가져온 소재를 흥정하는 소리로 시끌벅적했다. 스무명 남짓의 모험가들은 저마다 퀘스트 의뢰지와 가져온 물건들을 들고, 저마다 생환을 축하하듯 소리내어 자신의 공적을 자랑하느라 여념이 없었다.

길드 접수원의 안내에 따라 등록절차를 시작한 이안은 이름과 직업을 이야기하며 등록을 이어갔다.

그러니까.. 연금술사라고 하셨죠?

접수원은 뭔가 안타까운듯한 목소리로 확인을 해왔다. 흥미를 가지고 지켜보던 다른 모험가들은 이안의 직업이 확인되자, 싱겁다는 듯이 고개를 돌리며 자기들만의 화제로 이야기를 돌렸다.

연금술사.. 오직 생산을 위한 직업.. 전투에 대한 참여는 없다시피하고, 오직 전투 준비와 전투 후 뒤처리에 최적화된 직업. 

대형 파티라면 파티 숙소에 연금술사를 두고 운용이라고 하겠지만, 대부분의 연금술사들은 길드로부터 비싼 값에 재료를 사다 하루하루 포션이나 납품하는 일용직에 불과했다.

네.. 맞습니다.. 그리고 혹시 길드에서 연성을 해도 될까요?
가능해요. 대신 1회에 1실버입니다.

1실버. 죽은 모험가에서 찾아낸 돈을 써서 값을 지불할 수도 있었지만, 이안의 양심은 그것을 허락하지않았다.

제가 지금은 돈이 없는데..
응.. 괜찮아요. 대신 연성한 결과물을 보고 수수료를 제할 수 있고, 그것도 안된다면 길드에서 연성을 맡길테니 그 일을 해주셔도 되요.

리디아라고 자신을 소개한 접수원은 상냥하게 절차를 안내해준다. 그녀는 유능했지만, 무엇보다도 사람의 마음을 잘 이해해주었다. 필요한 것은 무엇인지, 그리고 준비해야할 것은 어떤 것이 있는지. 일이 익숙해서 반사적으로 나오는 것이 아닌, 호감과 인성에서 풍겨나오는 그 따뜻함. 이안은 그런 마음씀씀이가 너무 고마왔다. 

혹시..
네? 무슨..
오는 길에 숲에서 어떤 모험가를 수습해드렸습니다. 이곳 길드 소속이었다고 생각됩니다만..

이안이 조용히 죽은 모험가의 유품을 리디아 앞에 내놓았다. 1실버 20코퍼. 빈 물약병. 낡디 낡은 가방과 이제는 녹이슬어 이가 다 나간 단검까지. 

아..

맑은 눈의 리디아는 가만히 고개를 숙이며 명패를 확인했다. 어디에나 있을 하급 모험가의 명패. 이제 갓 D랭크를 단 사냥꾼의 명패라고했다. 숲에서 늑대를 처치하는 의뢰를 맡아 기분좋은 웃음을 띄우고는 숲으로 향했다는 그를 떠올리며, 이안은 왠지 안타까움을 느꼈다.

파티로 활동하지못하는 직업들은 많다. 흔히 말하는 필수직업, 전사, 도적, 성직자, 마법사를 제외하면 대부분의 직업들은 독자적으로 활동하거나 파티에 들고 싶으면 인맥이든 돈이든 최대한 이용해서 고용되어야했다. 같은 모험가들에게서도 느껴지는 계급사이의 현격한 차이. 그 계급의 피라미드에는 자신과 같은 생산직이 있었다. 모험가로 안된다면 결국 어딘가의 상점에 소속되어 연성을 통해 물품이나 만들어야하는 생산직.

고맙습니다. 길드에서 확인하여 진행하겠습니다. 혹시 어디에서 발견하셨는지..
아.. 이쯤입니다. 

숲의 지도에서 위치를 대충 갈음하여 무덤이 있을 위치를 알려주었다. 모든 이야기가 끝나고, 홀가분해진 이안은 그제야 자리를 떴다. 길드에 있는 연금술 실험대도 빌렸고, 이제 남은 자기 일을 하러 가려고 자리를 떴다.

* 재회. 그리고..



(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.) 

길드 한 켠에 마련된 식탁. 카페테리아 역할도 겸하는 길드의 1층에는 리라와 그녀의 친우로 보이는 한 마밥서가 같이 앉아있었다. 손짓을 섞어가며 이야기하는 마법사와 리라는 평상시의 대화를 이어갔지만, 이안은 왠지 그 리라에게서 서글픔 기운을 읽을 수 있을 것만 같았다.

식탁을 지나 지하로 내려가는 길에, 우연히 리라와 눈이 마주친 이안은 가만히 고개를 숙여 인사를 했다. 그런 그를 리라가 불러세웠다.

이안. 연금술사라고했죠? 잠깐 괜찮아요?

예기치못한 초대에 잠깐 당황했지만, 내어주는 자리에 앉아 가볍게 이야기를 시작했다. 출신지는 조금 멀리 떨어진 시골이고, 이제 막 연금술사 면허를 얻어 나왔다는, 여신이 지어준 배경이야기를 하고, 나이같은 사소한 소개를 한다.

어라. 나보다 연상이었네. 오빠라고 불러야할까요?
아닙니다. 한 살차이인데. 굳이.. 이안이라고 불러주세요.

너무나 사람좋고 활달하게 이야기하는 리라옆에는 이리스라고 스스로를 밝힌, 나이를 짐작하기도 어려운 엘프 여마법사가 있었다. 주로 리라가 이야기를 주도하고 이리스가 맞짱구를 치는 식으었지만, 살짝 차가워보이는 그녀의 표정에 이안은 몸이 움츠려드렸다.

잡담을 이어가던 중 가드의 행방을 묻는 이리스의 질문에 리라의 얼굴이 어두워졌다. 무엇인가 감을 잡았다는 이리스는 가드에 대한 독설을 내뱉었다.

달달한 꿀만 빨다가 이젠 됐다 이거야? 리라. 넌 도대체 언제까지 이럴래.
아니야. 그렇지는.
아니긴 뭐가 아니야. 도대체 몇번째야. 이 길드의 남자놈들은 모두 똑같아. 너를 이용만하고.
그러지마. 그런거 아니야.
도대체 그 놈의 고집은.

혀를 차는 이리스와 필사적으로 가드를 변호하는 리라. 짐작컨데, 리라의 이런 성품을 알고 적지않은 남자들이 그녀를 이용했을 것이라는 점을 짐작할 수 있었다. 길드에서도 가장 예쁘면서도 성격도 좋은 그녀를 남자들은 놓치지않았다. 집요하게 언제든 가지고 다닐 수 있는 꽃이라는 듯이, 남자 모험가들에게 그녀는 좋은 사냥감이나 다름 없었다.

오.. 리라.. 이제 솔로야. 나는 어때.
불곷으로 바싹 구워줄까? 어디서 수작이야.

천역덕스럽게 리라에게 접근해오는 남자를 이리스는 냉정한 눈으로 쫓아버렸다. 손에서는 타오르는 불꽃을 내세우며 시위하는 이리스를 보고, 남자는 '히익'하는 비명과 함께 도망갔다. 기세좋게 웃는 이리스를 보고 조금은 후련해진듯한 리라였지만, 그녀의 그늘을 보고나니 무엇인가 해주고 싶었다.

저기 리라..
응? 왜요, 이안?

순진 무구한 눈빛으로 향해오는 리라를 감히 정면으로 바라보지못하고 나는 말을 잇는다.

아.. 저.. 이제 연성하러 가는데요.. 혹시 필요한 것이..
어 그거 좋지.. 나 마나 포션 몇 개만 줘. 아까 보니 약초 꽤 쟁여놨던데, 한 두 개정도는 괜찮지, 응?
아.. 네에..

갑자기 끼어드는 이리스의 기백에 이안은 자기도 모르게 요구를 받아들였다. 이리스는 씨익 웃더니 리라에게 엄지를 척하니 들어보였다. 리라는 잠깐 생각하더니 생긋 웃으며 부탁을 했다. 지금까지 보아왔던 어떤 여성보다도 아름다운 웃음을 지으며..

음.. 그럼.. 상처재생 연고같은 것도 가능할까요?


* 연성시작



(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.) 

혈엽쑥이랑 은침 박하, 거미줄 풀이랑 감초 뿌리는 있고, 남은 건 용혈수지인가? 좀 살 수 있을까요?
그럼 가능하지, 한 병에 20코퍼.
지금은 돈이 없으니 연성하고 나서 제해도 될까요?
알았어. 대신 날려먹지나 마. 실험대 사용료에 재료비 날리면 꼬박 며칠동안은 길드에서 부려먹힐껄?
아 그리고 별빛 이끼도 조금만 부탁해요.
한 병에 50코퍼야. 적당히 쓰라고.

호탕한 관리인의 웃음을 뒤로, 이안은 준비된 재료와 빈 약병들을 모았다. 

재료를 다 준비하고 제작을 시작한다.

추출분류, 촉매작용...

원래라면 잘 갈아넣은 재료를 증류해서 모아야할 작업이 이안의 스킬로 순식간에 정리되기 시작했다.

'원래라면 이슬 왕골의 아침 이슬도 필요하지만 그건 증류수로 대신하자.'

가장 순수한 물이 필요한 마나 회복 물약을 위해 이안은 물에서 불순물을 모두 빼내고는 마나 물약을 만들기 시작했다. [분산사고]를 이용해 한손으로는 상처 재생 연고를, 다른 손으로는 마나 물약을 만드는 경이로운 조작은, 외딴 실험대를 사용하는 덕에 아무에게도 걸리지않고 진행할 수 있었다.

다 됐다.

보통이라면 몇시간에 걸쳐서 천천히 증류하고 반응을 일으켜야할 작업이, 이안의 [촉매 작용]덕에 순식간에 끝났다. 더불어 그의 명인급의 채집기술덕에 얻어진 재료들의 품질 또한 겨로가물에 영향을 미치며 만들어진 연고와 포션은 최고의 빛깔과 성능을 자랑하고 있었다.

그럼 남은 재료로 체력 포션과 스태미너 포션이라도 만들어두어야겠다.

아직 반도 사용하지않은 재료를 바라보고 이안은 다시 천천히 손을 놀리기 시작한다. [초감정]으로 얻어진 세상을 보는 눈 덕분에, 이안은 자신이 만들 수 있는 최선의 포션들을 만들기 시작한다. 그리고 막연히 누군가를 떠올린다. 아름다운 머리, 순수한 눈. 화려한 얼굴에 감춰진 순진무구한 일편단심. 그녀가 웃기를 간절히 바라는 마음을 담아 이안은 연성을 계속한다. 

* 슬픈 눈동자


(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.) 

어둠이 내리고, 마력 결정을 가로등이 빛을 내는 거리를 이안은 피곤에 지친 걸음을 내딛고 있었다. 저질 체력으로 연성을 계속하느라 지친 몸은 스태미너 포션을 마셔도 쉽게 피로가 가시지않았다. 피로에 찌든 이안이었지만, 그의 마음은 너무나 가벼웠다. 재료값과 실험대 이용료를 지불하기위해 포션을 납품했을 때 리디아의 놀란 얼굴. 비용을 모두 제하고도 남은 8실버 50코퍼. 그리고 마나포션과 재생연고를 받아든 이리스의 벙찐 얼굴과 리라의 행복했던 모습.

'뭐야 이거. 그 새 만들었다고. 그리고 이 마나량은 뭐야. 이거 완전 미친 품질이잖아.'

꼼꼼히 포션을 찍어 먹어보며 그 효과를 확인하던 이리스는 재료비가 아니라 아예 포션 값을 내겠다고했지만 정중히 사양했다. 어차피 며칠 동안의 숙박비용은 벌었고, 잠시 쉬면서 재료를 모아 좋은 납품처를 찾을 요량이었다. 그보다는 떨리는 손으로 재생연고를 받아들고는 살짝 물기어린 눈으로 고맙다고했던 리라의 얼굴이 가슴한편에 아려왔다.

'황금 햇살 여관'

리디아가 소개해준 여관에 지친 몸을 이끌고 들어서자, 갓구운 고소한 빵냄새와 진한 스튜냄새가 코 끝을 찔렀다. 숙박과 식사를 부탁하고 몇 코퍼의 돈을 지불한 후 이안은 겨우 엉덩이를 붙일 수 있었다.

소환 후 숲에서 노숙하고, 처음으로 겪어보았던 싸움, 그리고 첫 연성. 며칠 동안의 기억이 피로감을 극대화시키고 있었다.

아.. 빨리 먹고 올라가 좀 자야지.

멍하니 있는 것만으로도 회복이 이루어지는 [초회복]이라지만, 그래도 지금 이안에게는 푹신한 침대에서의 달콤한 잠만한 것이 없었다. 여관의 안주인이 빵과 스프를 가져와 이안의 앞에 놓자, 이안은 천천히 빵을 뜯어 스프에 찍어먹기 시작했다.

어이.. 그렇게 먹고서 어디 일하겠냐?

낯익은 목소리. 식탁앞에 푸른색 빛이 어른거리나 싶었더니 어느새 이리스가 앞에 자리를 잡고 합석을 했다. 갑작스런 상황에 생각이 끊긴 이안은 머뭇대다가 입을 떼었다.

어... 같은 여관에 계신줄은 몰랐습니다. 이리스님..
핫.. 이리스님이라니.. 리라의 친구니가 편하게 이리스라고 불러.
아.. 네.. 그럼 이리스..

입을 삐죽거리던 이리스는 익숙하게 움식을 시키고는 말없이 음식을 먹기 시작했다. 챙이 넓고 높은 고깔모자 아래에는 엘프의 귀가 삐죽 솟아있었고, 나이를 짐작할 수 없는 눈을 가진, 어린 소녀같은 얼굴을 가진 마법사는 얼굴에서는 생상하기힘든 인생의 깊은 감정이 가득 담긴 목소리로 이야기를 걸어왔다.

리라는 어떻게 알게 된거야?
어.. 알게 되다뇨?
뭐야. 네가 준 그 연고. 보통 품질이 아니야. 그리고 상처 재생연고는 제법 비싸기도하고. 그걸 그렇게 덜컥 주는 사람이 어디있겠어? 무슨 흑심이 있는거 아냐?

찌르듯이 물어오는 이리스. 길드에서 보았던 그녀의 태도가 질문에 겹쳐왔다. 자신의 친우를 어떻게해서든 감싸주려는 그 마음. 차가워보이는 그 태도 뒤에 숨겨진 따뜻한 성정. 이안은 왠지 가슴이 후련해지는 느낌을 받으며 답을 했다.

사실은 오늘 숲에서 우연히 만나게 되었습니다.

천천히 이야기를 시작하는 이안. 숲에 들어와 노숙을 한 이야기. 그리고 숲 복판에서의 전투와 한 영애아가씨를 구해준 이야기. 그리고 오로트에 들어와 등록하고 만난 것이 전부라는, 다소 시시한 이야기였다.
잠자코 이야기를 듣던 이리스가 뭔가 분에 겨운듯 씨근거렸다.

그러니까.. 그 망할 자식이.. 지금까지 일편단심인 리라를 차버리고 귀족한테 알랑방구나 뀌겠다고 지랄한단 말이지..

곱상한 엘프의 입에서 나올 것이라고는 상상도하지못했던 거친 말에 이안은 잠시 할 말을 잊었다. 딱히 반박할 말도 없었다. 어차피 모험가는 불안한 직업. 특히 전위에서 싸우는 전사나 도적은 그 생명이 더 짧았다. 인간기준으로 전사는 아무리 오래가도 40살, 도적은 30살이 넘으면 기량이 걲이기 마련이고, 이후에 어떻게든 살아갈 길을 찾아야했다. 
그들은 자신의 한계가 드러나기전에 어떻게해서든 좋은 위치를 차지해야했다. 아래에서 치고오는 젊은 세대에 밀리지않아야했고, 그 앞에는 이미 자리를 잡은 노련한 경험자들이 들어차있는 세계. 어쩌면 그렇기 때문에 행한 가드의 행동도 이해가 가는 것은 아니었다. 

이리스는 계속해서 리라에 대한 이야기를 이어갔다. 길드에서도 첫째, 둘째를 다툰다는 미모. 밝은 얼굴로 누구에게나 친절하게 대하는 태도. 도시의 모든 남자는 그런 아름다운 꽃을 손에 넣기 위해 앞다투어 리라에게 접근했다. 한 사람, 한 사람 리라는 항상 자신의 남자들에게 최선을 다했다. 육체를 원하는 사람에게는 육체를, 돈을 원하는 사람에게는 돈을. 아낌없이 자신의 모든 것을 남자에게 바치는 그녀를 남자들은 금새 떠나갔다.

물린다는 거지.. 망할 것들..

주변의 남자들을 차가운 눈으로 노려보며 이리스는 말을 했다.

리라는 한 번 사귀면 모든 것을 다 퍼준다고. 그걸 아니까 남자들은 더 이용하려고하지. 그래도 처음에는 한 달이라도 갔지. 시간이 지나면서 남자들에게 리라는 그냥 먹고 뱉는 칡뿌리같은 존재가 되어갔지. 단물만 다 빼먹고, 질린다고 차버리는 것들. 가드 녀석은 순번을 기다리듯 있다가 일주전에 사귀었지. 그리고 지금 이꼴이야. 처음에는 간도 쓸개도 빼줄 듯이 와서는 같이 방을 잡고 죽을 둥 살둥하더니, 오늘은 아예 얼굴도 안비친다고. 젠장. 망할 자식.

책상을 쾅 내리치는 이리스를 보며 손님들이 잠깐 이안의 테이블을 바라보지만, 분이 안풀려 씩씩거리는 이리스를 보고는 슬며시 고개를 돌린다. 마치 늘 그래왔던 화풀이를 본다는 듯이.

어.. 그럼 리라는 지금 어디에 있나요?

빵이 목에 메었는지, 약간 쉰 목소리로 묻는 질문에 이리스는 눈을 들었다.

글쎄.. 몰라. 아까 가드를 만난다고 나갔어. 가드는 백작의 저택에 머문다던데. 

왜인지는 몰랐다. 그냥 가야할 것만 같앗다. 이안은 자신과 이리스의 식사값을 모두 내고는 조용히 여관 문을 나섰다. 가로등이 거리를 밝게 비추고있지만, 길이 뻗은 앞쪽은 왠지 모를 슬픔과 어둠이 가득한 것 같았다. 


* 밤거리의 약속


(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라. 특히 리라의 애틋한 고마움이 잘 드러나도록 그녀의 마음을 표한하라.)
 
백작가로 가는 길은 질 좋은 포석이 깔린, 마차가 다니기 좋은 길이었다. 멀리 마법으로 조명을 밝힌 백작 저택의 화려한 위용이 보였지만, 이안의 마음은 무겁고 어둡기만 했다.

씹다버린 칡뿌리..

인간의 생리는 변하지 않는구나.. 나지막히 이안은 읊조렸다. 전생에서 겪었던 시간들이 환영처럼 눈앞에 떠올랐다. 도움이 필요할 때는 온갖 약속을 늘어놓다가, 막상 일이 마무리될 양이면 언제 그랬냐는듯이 얼굴을 바꾸는 사람들. 그런 모습에 지쳐가는 나날들에서 전생의 이안의 마음은 깎여지고, 금이가며 천천히 식어가고 있었다.

낮에 보았던 리라의 얼굴이 떠올랐다. 건네준 연고를 소중히 품에 안으며 물기어린 목소리로 감사를 표하던 리라. 어쩌면 다시 마음의 상처를 받을지라도 자신의 남자를 위해서는 무엇인가를 해주려는 그 마음. 그녀의 진심이 너무도 아릿하게 가슴을 저몄다.

한참을 걷던 이안은 닫혀진 백작가의 정문에 다다랐다. 그리고 거기에 그녀가 있었다. 한손에는 이안이 건네준 연고가 담긴 병을 꼭쥐고, 가녀린 어깨를 들썩인채로, 그녀의 눈부시게 아름다운 모습을 문앞의 가로등은 너무도 냉정하게 내리쬐고 있었다.

아.. 리라씨..

나지막히 이름을 부르는 이안의 목소리에 리라는 흠칫 몸을 떨고는 황급히 손으로 얼굴을 매만졌다. 이안을 바라보며 돌아선 그녀의 눈 아래는 붉게 물들어있었지만 오히려 환한 모습으로 웃으며 나를 맞이했다. 웃음이 이렇게 밝은데 이렇게 슬펐다. 

아.. 이안.. 왠일이야 이런 곳에..
어.. 리라씨가 여기에 있을거라고했어요. 이리스씨가..

머뭇대는 리라는 이안의 눈이 자신의 품에 있는 연고를 향한 것을 알아채고는 희미하게 웃으며 답했다.

숲속에서.. 가드가 좀 다친 것 같아서 이걸 주려고.. 그런데 괜찮데.. 백작의 치료사들 실력이 아주 좋아서.. 필요없다고.. 그냥 돌아가라고..

질끈하고 이안은 자기도 모르게 이를 앙다물었다. 연인으로부터 잔인한 헤어짐의 통보. 필요없다는 것은 연고가 아니었다. 가드는 너무나 쉽게 리라의 마음을 버리고 그녀를 버렸다.

그래서 돌려줘야할 것 같아. 미안 이안. 애써 만들어줬는데..

그녀가 떨리는 손으로 연고가 든 병을 이안 앞에 내어놓는다. 그리고 이안은 거칠어진 그녀의 손의 상처들을 두 눈으로 확인할 수 있었다. 사랑하는 사람과 함께 하기위해 온갖 어려움을 헤치던 그 손이, 이제는 버림받은 사랑의 증거를 어쩌지못하고 꼭 쥐고 있었다.

이안은 천천히 병을 잡았다. 손끝이 닿았다. 거칠지만 따스하고, 슬플정도로 아름다운 손. 이안은 천천히 병마개를 열어 연고를 손가락으로 떠냈다. 그리고 천천히 리라의 손에 발라주기 시작한다.

아..

따스한 리라의 손에 정신이 멍해지는 느낌을 받았던 이안이었지만 꾹 참고 천천히 그녀의 손에 어린 상처에 연고를 발라준다. 그렇게해서라도 그녀의 마음의 상처를 닦아주려는 듯이..

옅은 기분좋은 향내와 맑은 빛을 내며 연고는 순식간에 그녀의 손을 치료해간다. 

하지만 마음은 어떻게 해줄 수 없다. 눈에 보이지않는 상처야말로 더 깊을 수 밖에 없다는 이안이었다.

이안.. 이거 비싼거 같다고 이리스가 그러던데.. 내가 이거 돈을 낼테니까..
괜찮습니다. 리라..

리라의 눈 앞에, 피곤에 잔뜩찌든, 그렇지만 맑은 눈을 들어 이안이 이야기를 한다.

전 연금술사니까요. 얼마든지 만들어드릴게요. 다치면 말씀하세요. 열번이고, 백번이고 제가 꼭 고쳐드리겠습니다.

리라는 눈물 젖은 눈을 들어 이안을 또렷하게 쳐다본다. 늘 자신을 원해왔던 남자들. 하지만 이안은 주겠다고한다. 언제든. 열번이든. 백번이든. 
사랑의 고백. 사귀자는 유혹. 그 어떤 것도 아니었지만 리라의 마음은 그를 받아들이고 있었다. 강한 전사가 아니라도 좋았다. 남들에게 천시받더라도 좋았다. 지금 오직 그녀를 생각해주고, 그녀를 위해 무엇이든 해줄 것이라는 이 남자. 이안을 바라보며 리라의 눈에 한줄기 눈물이 흘러 떨어졌다. 슬픔이 아닌, 처음맞아보는 남자의 따뜻한 포용에 그녀는 더할나위없는 행복의 눈물을 흘렸다. 

* 사랑의 방식

(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.)
 
이안은 천천히 마무리하던 리라의 가죽갑옷에서 손을 떼었다. 한동안 이안의 일상은 바빴다. 사들인 재료를 가지고 각종 포션을 만들어 길드에 판매를 하고, 번 돈으로는 일상을 영위했다. 굳이 위험에 빠지지않고 적당히 일상을 영휘하려는 이안이었다. 하지만 리라의 반응은 달랐다.

이안한테 더부살이하는 것은 싫어.

같은 여관 옆방으로 이사온 리라는 이안이 제조한 포션으로 돈을 벌어 둘의 생활비를 쓰는 것에 격하게 반대했다.

나도 일할 수 있어. 이안의 돈에는 손을 안댈래. 

딱히 반대할 길이 없었던 이안은 궁여지책으로 리라의 갑옷을 손질해주기로 했다. [손재주]로 일상에서의 이안은 명인 수준의 결과물을 뽑아냈다. 요리는 물론, 재봉, 가죽공예에서의 솜씨는 최고였다. 체력과 근력이 낮은 탓에 대장장이일은 하지 못했지만, 아마 그것도 가능했다면 명검을 만드는 소드스미스로 이름을 날릴지도 몰랐다.

하지만 이안은 그런 것에는 관심없는 듯, 리라의 갑옷을 수리하는데 여념이 없었다. 길드에서 매입한 재료로 포션을 만들고, 생활비와 약간의 저축을 제외한 돈으로는 리라의 갑옷 강화재료를 사들였다. 지하동굴에서 돌을 먹고 사는 석식 슬라임의 점액, 평소에는 유연하지만 잘라 공기에 노출시키면 철사처럼 단단해지는 철선 덩굴, 유연하고 껍질이 질긴 은사버들을 모아 가죽 경화제를 만들었다.

[추출 분류]
[촉매 작용]
[기화]
[성분 동기화]

철선 동굴을 태워 얻은 숯가루를 슬라임의 점액에 녹이고, 은사버들에서 얻은 수액으로 겉에 바를 수 있는 혼합액을 만든다.

깨끗하게 [추출분류]로 가죽을 청소하고, 가죽에 혼합액이 잘 먹어들어가도록 [성분 동기화]를 걸었다. 마지막으로 경화속도를 높이기위해 [촉매 작용]을 건다.

여러 번 도포하고 말리는 과정을 거듭해야 하는 작업을 [촉매 작용]을 통해 순식간에 마친 이안은 이제 광물화된 가죽갑옷을 꼼꼼히 살피며, 철선 덩굴로 박음질을 하고 [촉매 작용]으로 순식간에 경화시켜 마무리했다.

완성된 가죽갑옷을 옷걸이에 걸으며 이안은 흐뭇하게 웃는다. 자신이 지켜줄 수는 없지만, 자신이 만든 갑옷으로 리라가 안전했으면 하는 마음. 비록 같이 전장에 서지는 못하더라도 반드시 지켜주고 싶은 이안의 마음이었다.

* 새로운 파티


(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.)

이리스가 자신의 찢어진 로브의 수선이나 포션 구입을 하기위해 오는 횟수가 점점 늘더니 아예 리라와 같은 방에 머물며 이안과 움직임을 같이했다.

정말 편리하네... 포션은 최상급에, 로브는 항상 만전의 수선이라니.

탄복하는 이리스를 리라가 짐짓 퉁명스레 몰아쳤다.

언제까지 이안을 부려먹을거야. 공짜로 부려먹는게 너무 심한거아냐?
무슨소리야. 내가 가져온 소재를 무시하는거야. 용혈수지에 얼마전에는 용의 콧김 버섯도 가져다주었잖아.
그러긴했지. 아주 가~아~끔

이안은 자기편을 들어주는 리라를 보며 싱긋웃었다. 돌돌돌 소리를 내며 돌아가는 재봉틀아래에는 이리스가 부탁한 로브에 마력문양을 넣는 작업이 한창이었다. 단단히 박힌 마력깃든 문양이 이리스의 로브에 빈틈없이 채워지자, 이리스는 감탄에 감탄을 연발했다.

대박. 이거 정말 물건이야. 내 마력이 최소한 20%는 향상된거같다고.
그 마력의 20%면 정말 대박이네. 이번에 어디 용이라도 잡는거야?

리라의 질문에 이리스는 픽하고 웃었다. 용이라니.. 아무리 자신이라도 혼자서는 무리라는 이야기. 지금 파티로는 꿈도 못꾼다는 이야기..

파티라뇨?
응? 아, 나 파티의 전위 마법사야. '은빛의 섬광'이라고 제법 유명한 파티지.

지금까지와는 몰랐던 이리스의 말에 이안은 놀라움을 금하지못했다. 오로트 도시에서도 상급에 속하는 파티 '은빛의 섬광'. 모험가 길드에 등록된 500명 중에서도 전력으로는 다섯손가락안에 든다는 강력한 파티였다. 도시에서 그들의 파티 하우스도 본적이 있었다. 강력한 성직자와 마법사를 보유한, 그야말로 막강하다못해 무시무시한 화력 파티.

근데, 우리도 요즘 좀 아쉬움이 많아.
뭔데? 최근에 몇 번 의뢰를 실패해서 그래?

리라의 걱정스런 질문에 이리스는 한숨을 쉰다. 막강한 화력을 가지고는 있지만 방어력은 절대적으로 열세였다. 가끔 리라를 임시 고용해서 써야할정도로 '은빛의 섬광'에는 제대로된 전위나 서포터가 적었다. 몰아붙이는 스타일의 화력전은 아무래도 전사에게는 부담이 컸고, 리라역시 폭풍처럼 몰아치는 파티 스타일에 적응이 되긴했어도, 정규 멤버로 들어가는데에는 살짝 망설이고 있었다.

제대로된 전위가 필요한데. 어디 없을까?

이리스의 질문에 딱히 답을 할 수는 없었다. 이안은 서포터, 그 중에서도 짐짝 취급 받는 연금술사. 만약 서포터로 합류를 원한다면 만사 OK겠지만, 제대로된 전위없는 파티에서 서포터는 아차하면 목숨을 잃어야하는 짐짝이나 다름없었다. 간혹 이리스가 와서 의뢰하는 제조나 제작역시 서포터의 부재를 충분히 암시하고 있었다. 저정도 규모에 서포터가 없는 상황은 그다지 좋은 모양새는 아니었다.

그럼 길드에 가보죠. 리디아씨가 혹시 새로운 전사를 발굴했을지도 모르니.

막연한 내말에 이리스는 입술을 삐죽인다.

있긴 있어. 대단한 중전사가. 이름이..
힐데라고 했어. 나도 그사람 알아. 굉장하지. 스펙도 훌륭한데, 근데 좀 이상해.

의문어린 시선으로 리라를 받아보자 이리스가 대신 답을 한다.

힐데라는 그 중전사. 완전 독고다이야. 어떤 사람하고도 파티를 맺지않아. 임시 파티를 한 번 해봤는데, 정말 실력이 대단하거든? 근데 고정 파티는 안만들어. 전사가. 믿겨져?


폭풍처럼 힐데라는 전사의 이야기를 풀어놓는 이리스. 그녀의 눈빛에는 어떻게해서든 그녀를 데려오고 싶다는 갈망이 폭주하고 있었다. 

* 힐데


(아래 내용을 이용하여 글을 작성하고, 가급적 원문을 유지한채로 지문과, 묘사, 대사를 강화하도록 하라.)

힐데를 영입하려는 이야기는 잠시 둥단되었다. 이리스가 새로운 의뢰를 받아 며칠동안 자리를 비우게 되어서였다. 

다녀올게. 이안이  만들어준 로브 덕에 이번에는 아주 한 방에 끝날 것아. 요즘 우리 파티 성직자 엘레나가 관심을 보이던데, 나중에 크게 부탁할지도 모르겠네.

호객을 하는 듯한 이리스의 말에 이안은 여신이 내려준 [좋은 인연]이 어째 여성에게만 통하는 것 같아 쓰게 웃었다. 

다녀와요 이리스. 너무 함부로 쓰지 말고요.
걱정말라고. 나 없는 동안에 리라랑 너무 붙어있으면 안돼.
아 진짜 이리스 무슨 물이야.

얼굴을 붉히는 리아를 놀리듯 이리스는 바삐 자신의 파티 하우스로 벌써 달려가고 있었다.

그나저나 우리도 간만에 길드에 가볼까요?

'우리'라는 말에 리라가 만면에 웃음을 띄며 팔짱을 낀다. 같은 숙소에 지내고, 식사시간마다 보기는 했지만, 일에 대해서는 그리 많은 활동을 같이하지는 못했다. 종종 재료를 얻기 위해 이안과 나갈 때면, 구름위에라도 나는 듯한 기분이었지만, 그럴 기회는 흔하지 않았다. 연금술사가 마물 퇴치같은 임무를 자청해서 맡을 일도 없었고, 길드도 리라만 믿고 두 사람에게 그런 의뢰를 주지도 않았다.

길드 게시판에서 어떤 의뢰를 받아볼까 찾아보던 이안을 리라가 옆구리를 찔러 주의를 끌었다.

저기 힐데에요.

이안의 눈이 리라가 가르키는 여성 중전사에게로 향했다..
큰 키와 단단한 몸집. 중전사다운 체격과 한눈에 봐도 대단해보이는 근력을 자랑하는 근육을 갖고 있었다. 다만 힐데의 장비는 군데군데 녹이 슬어있고, 금이 가는 등 제법 수리에 돈을 많이 서야할 것 같았다. 

왜 이 의뢰를 못받는다는 거야?

힐데의 다그침에 접수원 리디아가 안됐다는 표정으로 답을 했다.

힐데님. 당신이 뛰어난 전사인 것은 알지만 상대는 슬라임에요. 칼이나 도끼같은 날붙이로는 어떻게 할 수 없어요. 혹여라도 마법사가 있다면 힐데님이 방어하면서 어떻게든 할 수 있겠지만, 지금 그런 상태는 아니잖아요.

힐데는 말없이 얼굴을 붉힐 수 밖에 없었다. 마법사는 대부분 파티에 별도로 속해있었다. 귀중한 자원이기도하고, 왠만해서 파티에 들어온 마법사가 나가는 일도 드물었다. 파트에 있어 마법사나 성직자는 핵심 인력이었고, 그렇기때문에 늘 파티마다 실력있는 마법사와 성직자를 잡으려 안달이었다.

그러다보니 혼자 다니는 힐데는 마법사와 파티를 짠다는 것은 너무 어려웠다. 더구나  그간의 평판탓에 다른 파티는 왠만한면 그녀와 행동을 꺼려하고 있었다.

힐데가 의뢰를 포기하고 다른 의뢰를 찾으로 게시판에 가자 이안과 리라는 리디아에게 말을 걸었다.

힐데가 좀 곤란한 것 같은데..
아무래도 무장을 다시 수리하려면 꽤 큰 돈이 들 것 같아요.. 그래서 조금 무리인 의뢰지만 받아보려고 한 것 같은데.. 사정은 안타깝지만 위험한 상황을 길드에서도 두고 봐서는 안되느까요.

책임감이 넘치는 리디아의 논리는 빈틈이 없었다. 도시의 모험가는 되는 것도 쉽지는 않았다. 전사와 도적같은 일부 직업은 그 수를 조절해야했다. 필요이상의 무력 집단이 도시를 횡행하는 것은 치안이나 내부 소란등에 취약할 수 있었기때문에 도시는 늘 직업별로 일정정도를 유지하고자했다. 
마법사나 성직자는 숫자도 적기도했고, 방어 위주의 도시 구조상 매우 유용한 자원이었기때문에 항상 모집중이었지만 신의 가호나 마법적 재능이 높은 이들이 그리 쉽게 나타나지는 않았다.
이안 본인역시 모험가로 넘쳐도 별로 상관없는 생산직이기때문에 별문제없이 받아들여졌지, 전사나 도적이었다면 왠만한 실력자가 아닌 이상 거부되었을 터였다.

저희들이 그 의뢰를 해보면 어떨까요?

이안의 제안에 리디아는 눈을 동그랗게 떳다. 도적과 연금술사. 제대로된 화력도 나오지 않을터였고 무엇보다 딜러인 도적은 냉병기를 쓰는 직업이라 상성도 슬라임과는 극악이었다. 불허의 말이 리디아의 입에서 나오기전에 이안은 재빨리 말을 이었다.

이번에 얻은 화염 도마뱀의 소재가 있어요. 기름 주머니를 쓰면 화염 속성 오일이랑 투척용 폭탄을 만들 수 있습니다. 그리고 힐데가 앞에서 버텨준다면 충분히 해볼만할 것 같은데요.

이안의 제안은 꽤 설득력이 있었다. 힐데와 리라가 화염 인챈트 무기로 전위에 서고, 아무리 전투능력은 없다지만 투척정도는 가능한 이안이 폭탄을 던진다면 승산이 매우 높아졌다.. 

그래도..
불안 하시면 제가 만든 물건을 일단 보시고 결정하시죠. 

이안의 제안에 리디아는 고개를 끄덕였다. 지하 연성실로 들어간 이안은 바로 준비를 시작하다.

[추출분류]

화염도마뱀의 불꽃 주머니에서 조심스럽게 기름을 뽑아낸다. 원래대로라면 주머니를 찢어야햇고 잘못하면 폭발하는 위험한 물질이었지만, 이안의 기술로 순식간에 추출이 끝났다.

[촉매반응]

용혈수지를 녹인다음 뽑아낸 기름과 합쳐 끈적한 액이 되었다. 이어 '눈물 고추 나무 껍질 가루'를 섞어 저어주고는 유리병에 담았다.

이렇게 얻은 살라맨더 격분 오일을 덜어서 송진으로 굳힌다음 뇌석가루를 가운데에 넣어 소이탄을 만들었다.

완성된 인챈트 오일과 소이탄을 확인한 리디아는 의뢰를 허가해준다.

* 힐데와의 임시파티 준비 

슬라임의 독성 수액을 막기 위해 미끄러운 은빛 왁스(이슬왕골 왁스 추출물 + 백색 알칼리 진흙 + 감초 뿌리)를 만들어 세 사람의 방어구와 옷에 바른다. 군데 군데 찟겨진 힐데의 갑옷과 옷에 왁스를 바르느라 이안은 곤욕을 치른다. 생각보다 풍만한 힐데의 몸을 최대한 건드리지않게끔 노력하지만, 어쩔 수 없이 닿는 느낌이 야릇하기만하다. 힐데의 무장과 몸에 왁스를 발라주는 광경을 우연히 지켜본 리라는 힐데의 우람한 몸과는 비견되는 자신의 몸(그렇지만 육감적인)을 대비하고는 이안이 거유속성의 여성을 좋아하는 것은 아닌지 의심한다.
